//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYORN {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PropertyListResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyListResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SYORN.PropertyListResource", typeof(PropertyListResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSVersionID.
        /// </summary>
        internal static string _0 {
            get {
                return ResourceManager.GetString("0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSLatitudeRef.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSMeasureMode.
        /// </summary>
        internal static string _10 {
            get {
                return ResourceManager.GetString("10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSDOP.
        /// </summary>
        internal static string _11 {
            get {
                return ResourceManager.GetString("11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSSpeedRef.
        /// </summary>
        internal static string _12 {
            get {
                return ResourceManager.GetString("12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSSpeed.
        /// </summary>
        internal static string _13 {
            get {
                return ResourceManager.GetString("13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSTrackRef.
        /// </summary>
        internal static string _14 {
            get {
                return ResourceManager.GetString("14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSTrack.
        /// </summary>
        internal static string _15 {
            get {
                return ResourceManager.GetString("15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSImgDirectionRef.
        /// </summary>
        internal static string _16 {
            get {
                return ResourceManager.GetString("16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSImgDirection.
        /// </summary>
        internal static string _17 {
            get {
                return ResourceManager.GetString("17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSMapDatum.
        /// </summary>
        internal static string _18 {
            get {
                return ResourceManager.GetString("18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSDestLatitudeRef.
        /// </summary>
        internal static string _19 {
            get {
                return ResourceManager.GetString("19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSLatitude.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSDestLatitude.
        /// </summary>
        internal static string _20 {
            get {
                return ResourceManager.GetString("20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSDestLongitudeRef.
        /// </summary>
        internal static string _21 {
            get {
                return ResourceManager.GetString("21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSDestLongitude.
        /// </summary>
        internal static string _22 {
            get {
                return ResourceManager.GetString("22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSDestBearingRef.
        /// </summary>
        internal static string _23 {
            get {
                return ResourceManager.GetString("23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSDestBearing.
        /// </summary>
        internal static string _24 {
            get {
                return ResourceManager.GetString("24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSDestDistanceRef.
        /// </summary>
        internal static string _25 {
            get {
                return ResourceManager.GetString("25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageWidth.
        /// </summary>
        internal static string _256 {
            get {
                return ResourceManager.GetString("256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageLength.
        /// </summary>
        internal static string _257 {
            get {
                return ResourceManager.GetString("257", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BitsPerSample.
        /// </summary>
        internal static string _258 {
            get {
                return ResourceManager.GetString("258", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression.
        /// </summary>
        internal static string _259 {
            get {
                return ResourceManager.GetString("259", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSDestDistance.
        /// </summary>
        internal static string _26 {
            get {
                return ResourceManager.GetString("26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhotometricInterpretation.
        /// </summary>
        internal static string _262 {
            get {
                return ResourceManager.GetString("262", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageDescription.
        /// </summary>
        internal static string _270 {
            get {
                return ResourceManager.GetString("270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        internal static string _271 {
            get {
                return ResourceManager.GetString("271", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string _272 {
            get {
                return ResourceManager.GetString("272", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        internal static string _274 {
            get {
                return ResourceManager.GetString("274", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SamplesPerPixel.
        /// </summary>
        internal static string _277 {
            get {
                return ResourceManager.GetString("277", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XResolution.
        /// </summary>
        internal static string _282 {
            get {
                return ResourceManager.GetString("282", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YResolution.
        /// </summary>
        internal static string _283 {
            get {
                return ResourceManager.GetString("283", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlanarConfiguration.
        /// </summary>
        internal static string _284 {
            get {
                return ResourceManager.GetString("284", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResolutionUnit.
        /// </summary>
        internal static string _296 {
            get {
                return ResourceManager.GetString("296", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSLongitudeRef.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransferFunction.
        /// </summary>
        internal static string _301 {
            get {
                return ResourceManager.GetString("301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software.
        /// </summary>
        internal static string _305 {
            get {
                return ResourceManager.GetString("305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        internal static string _306 {
            get {
                return ResourceManager.GetString("306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string _315 {
            get {
                return ResourceManager.GetString("315", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhitePoint.
        /// </summary>
        internal static string _318 {
            get {
                return ResourceManager.GetString("318", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrimaryChromaticities.
        /// </summary>
        internal static string _319 {
            get {
                return ResourceManager.GetString("319", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExposureTime.
        /// </summary>
        internal static string _33434 {
            get {
                return ResourceManager.GetString("33434", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FNumber.
        /// </summary>
        internal static string _33437 {
            get {
                return ResourceManager.GetString("33437", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string _3432 {
            get {
                return ResourceManager.GetString("3432", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExposureProgram.
        /// </summary>
        internal static string _34850 {
            get {
                return ResourceManager.GetString("34850", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpectralSensitivity.
        /// </summary>
        internal static string _34852 {
            get {
                return ResourceManager.GetString("34852", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISOSpeedRatings.
        /// </summary>
        internal static string _34855 {
            get {
                return ResourceManager.GetString("34855", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OECF.
        /// </summary>
        internal static string _34856 {
            get {
                return ResourceManager.GetString("34856", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExifVersion.
        /// </summary>
        internal static string _36864 {
            get {
                return ResourceManager.GetString("36864", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTimeOriginal.
        /// </summary>
        internal static string _36867 {
            get {
                return ResourceManager.GetString("36867", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTimeDigitized.
        /// </summary>
        internal static string _36868 {
            get {
                return ResourceManager.GetString("36868", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComponentsConfiguration.
        /// </summary>
        internal static string _37121 {
            get {
                return ResourceManager.GetString("37121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompressedBitsPerPixel.
        /// </summary>
        internal static string _37122 {
            get {
                return ResourceManager.GetString("37122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShutterSpeedValue.
        /// </summary>
        internal static string _37377 {
            get {
                return ResourceManager.GetString("37377", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApertureValue.
        /// </summary>
        internal static string _37378 {
            get {
                return ResourceManager.GetString("37378", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrightnessValue.
        /// </summary>
        internal static string _37379 {
            get {
                return ResourceManager.GetString("37379", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExposureBiasValue.
        /// </summary>
        internal static string _37380 {
            get {
                return ResourceManager.GetString("37380", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxApertureValue.
        /// </summary>
        internal static string _37381 {
            get {
                return ResourceManager.GetString("37381", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubjectDistance.
        /// </summary>
        internal static string _37382 {
            get {
                return ResourceManager.GetString("37382", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeteringMode.
        /// </summary>
        internal static string _37383 {
            get {
                return ResourceManager.GetString("37383", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightSource.
        /// </summary>
        internal static string _37384 {
            get {
                return ResourceManager.GetString("37384", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash.
        /// </summary>
        internal static string _37385 {
            get {
                return ResourceManager.GetString("37385", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FocalLength.
        /// </summary>
        internal static string _37386 {
            get {
                return ResourceManager.GetString("37386", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MakerNote.
        /// </summary>
        internal static string _37500 {
            get {
                return ResourceManager.GetString("37500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserComment.
        /// </summary>
        internal static string _37510 {
            get {
                return ResourceManager.GetString("37510", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubSecTime.
        /// </summary>
        internal static string _37520 {
            get {
                return ResourceManager.GetString("37520", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubSecTimeOriginal.
        /// </summary>
        internal static string _37521 {
            get {
                return ResourceManager.GetString("37521", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubSecTimeDigitized.
        /// </summary>
        internal static string _37522 {
            get {
                return ResourceManager.GetString("37522", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSLongitude.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlashPixVersion.
        /// </summary>
        internal static string _40960 {
            get {
                return ResourceManager.GetString("40960", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorSpace.
        /// </summary>
        internal static string _40961 {
            get {
                return ResourceManager.GetString("40961", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PixelXDimension.
        /// </summary>
        internal static string _40962 {
            get {
                return ResourceManager.GetString("40962", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PixelYDimension.
        /// </summary>
        internal static string _40963 {
            get {
                return ResourceManager.GetString("40963", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlashEnergy.
        /// </summary>
        internal static string _41483 {
            get {
                return ResourceManager.GetString("41483", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpatialFrequencyResponse.
        /// </summary>
        internal static string _41484 {
            get {
                return ResourceManager.GetString("41484", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FocalPlaneXResolution.
        /// </summary>
        internal static string _41486 {
            get {
                return ResourceManager.GetString("41486", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FocalPlaneYResolution.
        /// </summary>
        internal static string _41487 {
            get {
                return ResourceManager.GetString("41487", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FocalPlaneResolutionUnit.
        /// </summary>
        internal static string _41488 {
            get {
                return ResourceManager.GetString("41488", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubjectLocation.
        /// </summary>
        internal static string _41492 {
            get {
                return ResourceManager.GetString("41492", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExposureIndex.
        /// </summary>
        internal static string _41493 {
            get {
                return ResourceManager.GetString("41493", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SensingMethod.
        /// </summary>
        internal static string _41495 {
            get {
                return ResourceManager.GetString("41495", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSource.
        /// </summary>
        internal static string _41728 {
            get {
                return ResourceManager.GetString("41728", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SceneType.
        /// </summary>
        internal static string _41729 {
            get {
                return ResourceManager.GetString("41729", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFAPattern.
        /// </summary>
        internal static string _41730 {
            get {
                return ResourceManager.GetString("41730", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSAltitudeRef.
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEGInterchangeFormat.
        /// </summary>
        internal static string _513 {
            get {
                return ResourceManager.GetString("513", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEGInterchangeFormatLength.
        /// </summary>
        internal static string _514 {
            get {
                return ResourceManager.GetString("514", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YCbCrCoefficients.
        /// </summary>
        internal static string _529 {
            get {
                return ResourceManager.GetString("529", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YCbCrSubSampling.
        /// </summary>
        internal static string _530 {
            get {
                return ResourceManager.GetString("530", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YCbCrPositioning.
        /// </summary>
        internal static string _531 {
            get {
                return ResourceManager.GetString("531", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceBlackWhite.
        /// </summary>
        internal static string _532 {
            get {
                return ResourceManager.GetString("532", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSAltitude.
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSTimeStamp.
        /// </summary>
        internal static string _7 {
            get {
                return ResourceManager.GetString("7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSSatellites.
        /// </summary>
        internal static string _8 {
            get {
                return ResourceManager.GetString("8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPSStatus.
        /// </summary>
        internal static string _9 {
            get {
                return ResourceManager.GetString("9", resourceCulture);
            }
        }
    }
}
